# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u7ad9\u70b9\u540d')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True, verbose_name='\u542f\u7528\u76d1\u6d4b')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sites', models.ManyToManyField(blank=True, to='analyse.Site', verbose_name='\u7ba1\u7406\u7684\u7ad9\u70b9')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
