# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('region_id', models.IntegerField(verbose_name='\u533a\u57dfID')),
                ('region_type', models.CharField(choices=[(b'province', '\u7701'), (b'city', '\u57ce\u5e02')], max_length=32)),
                ('child_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analyse.Region', verbose_name='\u7236\u7ea7')),
            ],
        ),
    ]
